import { Post } from "../interfaces/post.interface";

export const posts: Post[] = [
    {
        id: 1,
        title: 'Exploring the Alps',
        brief: 'Discover the breathtaking beauty of the Alps and the best hiking trails.',
        text: 'The Alps are a stunning mountain range that spans across several European countries. This guide will take you through the most scenic hiking trails, charming villages, and must-visit spots for an unforgettable adventure.',
        author: 'John Doe',
        imageUrl: 'https://plus.unsplash.com/premium_photo-1688655246851-1d2dadffd92f?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        category: { id: 1, title: 'Travel' },
        publicationDate: new Date('2023-01-15'),
    },
    {
        id: 2,
        title: 'A Weekend in Paris',
        brief: 'Experience the charm of Paris in just two days.',
        text: 'Paris, the city of love, offers a unique blend of history, art, and culture. This guide will help you make the most of your weekend with recommendations for iconic landmarks, cozy cafes, and hidden gems.',
        author: 'Jane Smith',
        imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        category: { id: 2, title: 'City Breaks' },
        publicationDate: new Date('2023-02-10'),
    },
    {
        id: 3,
        title: 'Safari Adventure in Kenya',
        brief: 'Get up close with wildlife on a thrilling safari in Kenya.',
        text: 'Kenya is home to some of the most diverse wildlife on the planet. This article explores the best safari destinations, tips for spotting the Big Five, and how to make your trip eco-friendly.',
        author: 'Alice Johnson',
        imageUrl: 'https://images.unsplash.com/photo-1494783367193-149034c05e8f?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        category: { id: 3, title: 'Adventure' },
        publicationDate: new Date('2023-03-05'),
    },
    {
        id: 4,
        title: 'Relaxing in the Maldives',
        brief: 'Unwind on the pristine beaches of the Maldives.',
        text: 'The Maldives is a tropical paradise known for its crystal-clear waters, luxurious resorts, and serene beaches. Learn about the best islands to visit, activities to try, and tips for a relaxing getaway.',
        author: 'Robert Brown',
        imageUrl: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        category: { id: 4, title: 'Luxury' },
        publicationDate: new Date('2023-04-20'),
    },
    {
        id: 5,
        title: 'Cultural Journey through Japan',
        brief: 'Immerse yourself in the rich culture and traditions of Japan.',
        text: 'Japan offers a unique blend of ancient traditions and modern innovation. This guide covers everything from historic temples and tea ceremonies to bustling cities and culinary delights.',
        author: 'Emily Davis',
        imageUrl: 'https://plus.unsplash.com/premium_photo-1664368832403-38da21a65fed?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        category: { id: 5, title: 'Culture' },
        publicationDate: new Date('2023-05-15'),
    },
    {
        id: 6,
        title: 'Road Trip Across the USA',
        brief: 'Explore the diverse landscapes of the United States on an epic road trip.',
        text: 'The USA is a vast country with diverse landscapes, from deserts and mountains to forests and coastlines. This guide provides tips for planning your route, must-see destinations, and how to make the most of your road trip.',
        author: 'Michael Wilson',
        imageUrl: 'https://images.unsplash.com/photo-1741209488962-4294c0b48d4a?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        category: { id: 6, title: 'Road Trips' },
        publicationDate: new Date('2023-06-10'),
    },
];